[server]
maxUploadSize = 200
enableStaticServing = false

[theme]
base = "light"
primaryColor = "#5C67F2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
